### ISSUE TITLE
No matter the actual value, Delay is shown to be 274.9s

### ISSUE THREAD

**Issue by pavolpolacek** [tum-lkn/tcgui#12]
No matter the actual value I set, **Delay is shown to be 274.9s**. Other parameters like loss etc seem to be OK. The delay I observe is however correct, so tc works as it should, but the problem is with the indicated value.

Setting the values:
![noSettings](https://user-images.githubusercontent.com/37660551/71974618-33ea1380-3212-11ea-8e83-0b43c6712aad.png)

Values shown:
![settings01](https://user-images.githubusercontent.com/37660551/71974619-33ea1380-3212-11ea-8a18-9ae7af1bfdbc.png)

I have installed tcgui on Raspberry Pi 4 B and Raspbian 10 buster with kernel 4.19.75-v7l+.

**Comment by hofbi** [comment]
Do you get the same value when you read the delay with the tc cli?

**Comment by pavolpolacek** [comment]
Hi Markus,

it seems to be a problem with tc itself and not with tcgui. The indicated value for delay is a  off, even but it adds the correct amount of delay. After I add 10ms, it delays the packets by 10ms, but shows 274.9.

With no settings I get:
pi@raspberrypi:~ $ tc qdisc show  dev eth1
qdisc pfifo_fast 0: root refcnt 2 bands 3 priomap  1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1
pi@raspberrypi:~ $ tc qdisc show  dev eth2
qdisc pfifo_fast 0: root refcnt 2 bands 3 priomap  1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1

After I have set everything to "10" I get the following output:
pi@raspberrypi:~ $ tc qdisc show  dev eth1
qdisc netem 8003: root refcnt 2 limit 10 delay 274.9s  274.9s loss 10% duplicate 10% reorder 10% corrupt 10% rate 10Mbit gap 1
pi@raspberrypi:~ $ tc qdisc show  dev eth2
qdisc netem 8004: root refcnt 2 limit 10 delay 274.9s  274.9s loss 10% duplicate 10% reorder 10% corrupt 10% rate 10Mbit gap 1
pi@raspberrypi:~ $ 

You can close this issue. No work is necessary from your side.
