### ISSUE TITLE
raise TypeError

### ISSUE THREAD

**Issue by sschalamon** [tum-lkn/tcgui#17]
The following error occurs when calling "python3 main.py":
<code>
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    pattern = re.compile(args.regex)
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 303, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern
</code>
My environment:
Python 3.8, Ubuntu 20.04.2 LTS, but same error with recent Linux Mint.
No Error when calling "python3 main.py --help"

**Comment by hofbi** [comment]
Thanky you for reporting. Fixed with the mentioned commit.

**Comment by sschalamon** [comment]
Tnx a lot, tested and confirmed from my side.
Kind regards, Stefan

Am 20. Juni 2021 21:28:35 schrieb Markus Hofbauer ***@***.***>:
>
> Thanky you for reporting. Fixed with the mentioned commit.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> [
> {
> ***@***.***": "http://schema.org",
> ***@***.***": "EmailMessage",
> "potentialAction": {
> ***@***.***": "ViewAction",
> "target": "https://github.com/tum-lkn/tcgui/issues/17#issuecomment-864600854",
> "url": "https://github.com/tum-lkn/tcgui/issues/17#issuecomment-864600854",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> ***@***.***": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]



Mit Aqua Mail Android
https://www.mobisystems.com/aqua-mail
