### ISSUE TITLE
Reorder covariance/correlation field in website aren't updating

### ISSUE THREAD

**Issue by eliaahadi** [tum-lkn/tcgui#4]
I was just testing the input fields and noticed that some fields aren't updating the website compared to the other fields.

Delay, loss, and reorder fields with current and variance/correlation values don't render after putting in a value. Screenshot below I just tested values of "2". The other fields did populate the current and variance/correlation values. 

If this isn't a proper quick test, please let me know the correct way. Thank you.

![image](https://user-images.githubusercontent.com/9751505/54729936-754cfc00-4bc9-11e9-9c3a-30d2879dddb8.png)

Also, I saw the log and it says I need to specify a delay which I thought I did in screenshot and log below.

![image](https://user-images.githubusercontent.com/9751505/54730200-f3f66900-4bca-11e9-9f9d-76e157ae5c7a.png)

![image](https://user-images.githubusercontent.com/9751505/54730245-3ddf4f00-4bcb-11e9-8e4a-e46e2d0a127c.png)

Ok, after testing more, I managed to get all the fields working. I just had to wait and input the right fields while looking at the log. Please close this issue.

**Comment by beneeh** [comment]
> Ok, after testing more, I managed to get all the fields working. I just had to wait and input the right fields while looking at the log. Please close this issue.

Thank you for submitting the issue. I will close it now as you requested. Let us know if there are some other bugs/improvements you want us to fix/implement.

Greetings Bene
